/*alert('My text here');
console.log('My text here');
document.write('My text here');*/
var num = 0;
num = num + 2;
num = num * 3;
num = num / 2;
num++;
num--;
num += 1;
num -= 2;
num *= 3;
num /= 2;
num %= 3;
document.write(' >>> num == 1: ', (num == 1));
document.write(' >>> num === 1: ', (num === 1));
document.write(' >>> num != 1: ', (num != 1));
document.write(' >>> num > 1: ', (num > 1));
document.write(' >>> num < 1: ', (num < 1));
document.write(' >>> num >= 1: ', (num >= 1));
document.write(' >>> num <= 1: ', (num <= 1));
document.write(' >>> true && false: ', (true && false));
document.write(' >>> true || false: ', (true || false));
document.write(' >>> !true: ', (!true));
